version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - the-list-db:/etc/the-list
    stdin_open: true
volumes:
  the-list-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /etc/the-list 

